language: java
sudo: true

jdk:
 - oraclejdk8

install:
 - mvn -N io.takari:maven:wrapper

addons:
  hosts:
   - kafka

env:
  global:
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092

before_install:
- wget http://www.us.apache.org/dist/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz -O kafka.tgz
- mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
- nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
- sleep 5

script:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn test

branches:
  only:
    - master
